#!/bin/bash
STATE=$(pactl list sources | grep -i alsa_input.pci-0000_00_1b.0.analog-stereo -A 6 | tail -n 1 | sed 's/[[:space:]]//g')
if [ $STATE == 'Mute:yes' ];
then
    notify-send -t 500 "Unmuted microphone"
else
    notify-send -t 500 "Muted microphone"
fi
pactl set-source-mute alsa_input.pci-0000_00_1b.0.analog-stereo toggle
