#!/bin/sh
# solarized swaylock

# color definitions
base03=002b36
base02=073642
base01=586e75
base00=657b83
base0=839496
base1=93a1a1
base2=eee8d5
base3=fdf6e3
yellow=b58900
orange=cb4b16
red=dc322f
magenta=d33682
violet=6c71c4
blue=268bd2
cyan=2aa198
green=859900
transparent=00000000
radius=80

LOCKBG="/tmp/.lockbg.png"

swaygrab $LOCKBG
convert $LOCKBG -blur 0x8 -channel RGBA $LOCKBG
swaylock -i $LOCKBG $@ \
	--bshlcolor $orange \
	--insidecolor $base02 --insidevercolor $green --insidewrongcolor $red \
	--keyhlcolor $blue --line-uses-ring \
       	--ringcolor $base00 --ringvercolor $green --ringwrongcolor $red \
	--separatorcolor $transparent --textcolor $base3 \
	--indicator-radius $radius
rm $LOCKBG

swaymsg mode default
